.TH "src/main.cpp" 3 "Mar 21 Mag 2024" "Version 3.0" "BATTAGLIA NAVALE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'librerie\&.h'\fP
.br

.SS "Definizioni"

.in +1c
.ti -1c
.RI "#define \fBN\fP   9"
.br
.in -1c
.SS "Funzioni"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Codice main del gioco\&. "
.in -1c
.SH "Documentazione delle definizioni"
.PP 
.SS "#define N   9"

.SH "Documentazione delle funzioni"
.PP 
.SS "int main ()"

.PP
Codice main del gioco\&. 
.PP
\fBRestituisce\fP
.RS 4
int per fine del gioco 
.RE
.PP
Inizializzo il generatore di numeri casuali
.PP
inizializzazioni delle variabili del gioco
.PP
Pulitura dei 2 array dei campi in modo da avere matrici pulite
.PP
Prima schermata del gioco
.PP
Istruzioni di gioco
.PP
CIclo inserimento navi in griglia
.PP
Inserimento navi avversario automatico
.PP
Inizio della sfida vera e propria
.PP
verifica se uno dei due giocatori ha vinto
.PP
Schermata che identifica il vincitore
.SH "Autore"
.PP 
Generato automaticamente da Doxygen per BATTAGLIA NAVALE a partire dal codice sorgente\&.
